### ISSUE TITLE
SyntaxError: JSON5: invalid character '<' at 1:1

### ISSUE THREAD

**Issue by mhay10** [tobiastimm/code-theme-converter#37]
I not sure what I am doing wrong but I am getting this error when trying to convert a vscode theme to a sublime theme

The command I enter is: `code2subl https://github.com/drywolf/dark-plus-plus-theme`
I get the following output:
```
Fetching repo
Converting 1 theme
🎉 Successfully converted the vscode theme for sublime text!
C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:287
        throw invalidChar(read())
        ^

SyntaxError: JSON5: invalid character '<' at 1:1
    at syntaxError (C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:1028:12)
    at Object.value (C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:287:15)
    at lex (C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\json5\lib\parse.js:25:17)
    at C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\code-theme-converter\dist\util\vscode.js:54:57
    at C:\Users\MYUSERNAME\scoop\persist\yarn\global\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3) {
  lineNumber: 1,
  columnNumber: 1
}
```

**Comment by tobiastimm** [comment]
For me it seems like the theme is containing an invalid character
