### ISSUE TITLE
code2idea throws `Trace: Error: ENOENT: no such file or directory, scandir`

### ISSUE THREAD

**Issue by cyberquarks** [tobiastimm/code-theme-converter#47]
I tried to convert a VS code repository:
```

> code2idea https://github.com/enkia/enki-theme.git
Fetching repo
Trace: Error: ENOENT: no such file or directory, scandir 'C:\Users\cyberquarks\AppData\Local\Temp\code-theme-converter\repo\themes'
    at Object.<anonymous> (C:\Users\cyberquarks\AppData\Roaming\npm\node_modules\code-theme-converter\dist\idea\convert.js:88:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\cyberquarks\AppData\Roaming\npm\node_modules\code-theme-converter\dist\idea\convert.js:6:65)
🎉 Successfully converted the vscode theme for IDEA!
```

Has anyone encountered this issue?

**Comment by mhanberg** [comment]
I get this as well.

**Comment by SanJacobs** [comment]
I am too, both on Windows and Debian.

```
D:\Downloads>code2subl https://github.com/k4ustu3h/jamt-vscode#main
Fetching repo
Error: ENOENT: no such file or directory, scandir 'C:\Users\Athena\AppData\Local\Temp\code-theme-converter\repo\themes'
🎉 Successfully converted the vscode theme for sublime text!
```

**Comment by jewellscott** [comment]
I got the same error on Mac Ventura.
