### ISSUE TITLE
SyntaxError: JSON5: invalid character '<' at 1:1

### ISSUE THREAD

**Issue by swift98** [tobiastimm/code-theme-converter#51]
when use code2idea https://github.com/EryouHao/brackets-light-pro.git
i get the following error:

/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:287
        throw invalidChar(read())
        ^

SyntaxError: JSON5: invalid character '<' at 1:1
    at syntaxError (/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:1028:12)
    at Object.value (/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:287:15)
    at lex (/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/usr/local/lib/node_modules/code-theme-converter/node_modules/json5/lib/parse.js:25:17)
    at /usr/local/lib/node_modules/code-theme-converter/dist/util/vscode.js:54:57
    at /usr/local/lib/node_modules/code-theme-converter/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  lineNumber: 1,
  columnNumber: 1
}

**Comment by tobiastimm** [comment]
code2idea isn't working, like written within the description
