### ISSUE TITLE
code2idea and code2subl are not able to checkout the repo

### ISSUE THREAD

**Issue by charitarthchugh** [tobiastimm/code-theme-converter#55]
Here is the following error:
```bash
~
❯ code2idea https://github.com/piousdeer/vscode-adwaita.git
Fetching repo
Trace: Error: 'git checkout' failed with status 1
    at Object.<anonymous> (/home/cc/.npm/lib/node_modules/code-theme-converter/dist/idea/convert.js:88:21)
    at Generator.throw (<anonymous>)
    at rejected (/home/cc/.npm/lib/node_modules/code-theme-converter/dist/idea/convert.js:6:65)
  Successfully converted the vscode theme for IDEA!
```
Same for code2subl
```
❯ code2subl "https://github.com/piousdeer/vscode-adwaita"
Fetching repo
Error: 'git checkout' failed with status 1
Successfully converted the vscode theme for sublime text!
```
Tested against node 18.3.0 and  16.15.1 
I have been able to reproduce this behavior in a container as well (`node:latest` & `node:16`)

**Comment by agenordebriat** [comment]
Try again using `code2subl https://github.com/piousdeer/vscode-adwaita#main` instead. Works for me!

**Comment by charitarthchugh** [comment]
Worked for me as well with code2idea.

**Comment by agenordebriat** [comment]
Yup.

**Comment by tobiastimm** [comment]
Yeah I didn't have the time to introduce any changes in the last year. Probably there needs to be a check for master/main

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ishanavasthi, @138over, @hossein-ansari, @coderosh-zz, @brainfried, @stereo720712, @nndcneyut98, @joetm, @Sleepy978, @paulocoghi, @radio24, @KarlTheCool, @n0hot, @feidianbo, @yikeda6616, @Michaelobot1, @lqm0408, @a-dera, @geekerrun, @josilenonascimento, @ehlodex, @s-kostyaev, @chenmingming, @vojenfr, @CIPHERTron, @realzombiegeek, @flawedworld, @kyoz, @mashaalAl3nizy, @light60, @Stingertough, @j0hncc, @0zul, @tth05, @mikemertens15, @T-Induwara, @tuanductran, @stockime, @alisha, @hellsan631, @userid451, @zaqzaq, @speed-archery, @rolandog, @brianbgarber, @k-kruglov, @huseyin1419, @manuelmair, @red-co, @douzifly

**Comment by Lake-Jee** [comment]
Adding the `#<branch-name>` worked for me as well. Ty @agenordebriat !! <3
