### ISSUE TITLE
Cannot read property 'id' of undefined on Andromeda theme

### ISSUE THREAD

**Issue by 1337jick** [tobiastimm/code-theme-converter#62]
Hey, thank you for the hardwork. Wish I could apply Andromeda theme on webstorm

https://github.com/EliverLara/Andromeda

This is the trace

`Trace: Error: EEXIST: file already exists, mkdir '/Users/macbook/Downloads/code-theme-converter-master/Andromeda/resources'
    at /Users/macbook/Downloads/code-theme-converter-master/dist/idea/convert.js:81:49
Trace: TypeError: Cannot read property 'id' of undefined
    at /Users/macbook/Downloads/code-theme-converter-master/dist/idea/convert.js:81:49
Trace: TypeError: Cannot read property 'id' of undefined
    at /Users/macbook/Downloads/code-theme-converter-master/dist/idea/convert.js:81:49
Trace: TypeError: Cannot read property 'id' of undefined
    at /Users/macbook/Downloads/code-theme-converter-master/dist/idea/convert.js:81:49
Trace: TypeError: Cannot read property 'id' of undefined
    at /Users/macbook/Downloads/code-theme-converter-master/dist/idea/convert.js:81:49`

**Comment by tobiastimm** [comment]
Sorry for the late reply, unfortunately, I never finished the code2idea converter. I would need to revisit those
